#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

cookbook 'apache2', '>= 1.0.0'

cookbook 'windows-jazz',
   :github => 'lonniev/windows-jazz'

cookbook 'java'

cookbook 'maven'

cookbook 'git'

